### ISSUE TITLE
General software refactoring & performance improvements

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/exporter#5]
```
Refactoring & general performance improvements.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 31 Jul 2013 at 10:29

**Comment by canadainc** [comment]
ca08f2f7df4b88c6d4157d2f0b54a238b4b037d1

**Comment by canadainc** [comment]
Verified with GCR v3.0.0.0
R135 10.3.1.2744
R070 10.2.1.3508
