### ISSUE TITLE
Use interactive tutorials

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/exporter#61]
```
Don't use system default ones
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 5 Dec 2014 at 2:47

**Comment by canadainc** [comment]
1f93218d6f001d4f559e3fdd0401462e50f20128

**Comment by canadainc** [comment]
Verified with GCR 3.0.0.0
R144 10.3.2
R072 10.3.1.2744
R070 10.2.1.3508
