### ISSUE TITLE
Enable touch-sensitive keyboard scrolling on Passport

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/exporter#70]
```
ListView:
scrollRole: ScrollRole.Main
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 15 Jan 2015 at 9:51

**Comment by canadainc** [comment]
984e414d13c1065aa0c84ba158f23cf4aa20b601

**Comment by canadainc** [comment]
Duplicates Capacitive keyboard support #90
